//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.20 at 04:48:39 PM CEST 
//


package nl.rug.search.tools.teianalytics.teismodel;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.rug.search.tools.teianalytics.teismodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.rug.search.tools.teianalytics.teismodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ListBibl }
     * 
     */
    public ListBibl createListBibl() {
        return new ListBibl();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct }
     * 
     */
    public ListBibl.BiblStruct createListBiblBiblStruct() {
        return new ListBibl.BiblStruct();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Monogr }
     * 
     */
    public ListBibl.BiblStruct.Monogr createListBiblBiblStructMonogr() {
        return new ListBibl.BiblStruct.Monogr();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Monogr.Imprint }
     * 
     */
    public ListBibl.BiblStruct.Monogr.Imprint createListBiblBiblStructMonogrImprint() {
        return new ListBibl.BiblStruct.Monogr.Imprint();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Analytic }
     * 
     */
    public ListBibl.BiblStruct.Analytic createListBiblBiblStructAnalytic() {
        return new ListBibl.BiblStruct.Analytic();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Analytic.Author }
     * 
     */
    public ListBibl.BiblStruct.Analytic.Author createListBiblBiblStructAnalyticAuthor() {
        return new ListBibl.BiblStruct.Analytic.Author();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Analytic.Author.PersName }
     * 
     */
    public ListBibl.BiblStruct.Analytic.Author.PersName createListBiblBiblStructAnalyticAuthorPersName() {
        return new ListBibl.BiblStruct.Analytic.Author.PersName();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Monogr.Title }
     * 
     */
    public ListBibl.BiblStruct.Monogr.Title createListBiblBiblStructMonogrTitle() {
        return new ListBibl.BiblStruct.Monogr.Title();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Monogr.Imprint.BiblScope }
     * 
     */
    public ListBibl.BiblStruct.Monogr.Imprint.BiblScope createListBiblBiblStructMonogrImprintBiblScope() {
        return new ListBibl.BiblStruct.Monogr.Imprint.BiblScope();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Monogr.Imprint.Date }
     * 
     */
    public ListBibl.BiblStruct.Monogr.Imprint.Date createListBiblBiblStructMonogrImprintDate() {
        return new ListBibl.BiblStruct.Monogr.Imprint.Date();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Analytic.Title }
     * 
     */
    public ListBibl.BiblStruct.Analytic.Title createListBiblBiblStructAnalyticTitle() {
        return new ListBibl.BiblStruct.Analytic.Title();
    }

    /**
     * Create an instance of {@link ListBibl.BiblStruct.Analytic.Author.PersName.Forename }
     * 
     */
    public ListBibl.BiblStruct.Analytic.Author.PersName.Forename createListBiblBiblStructAnalyticAuthorPersNameForename() {
        return new ListBibl.BiblStruct.Analytic.Author.PersName.Forename();
    }

}
